### PR TITLE
Fix to reuse buffer in decodeDataPage

### LINKED ISSUE #359: Memory usage increase in #350
Our benchmarks are showing a significant memory increase after #350. One in particular is increasing from 33MB/op to 350MB/op, via the allocation in [column.decodeDataPage](https://github.com/parquet-go/parquet-go/pull/350/files#diff-305df432ba0cbb43811c59f0b3ed81912bb00b3f7d054cdc366d1acaa1e21900R716).   This benchmark reads many dictionary byte array pages.

The comment mentions the prevention of buffer reuse issues if callers retain values.  Is this a separate case not covered by the existing mechanisms callers have to manage this, including `value.Clone()` and `page.Retain()`?   Tempo makes use of `value.Clone()` specifically to retain strings, expecting the buffers will be reused.

What are your thoughts on best way to avoid this alloc?

### PR DESCRIPTION
**Pull request by mdisibio**
Fixes #359

This PR illustrates the changes that are needed to both remove the alloc from decodeDataPage and prevent all tracebuf leak warnings. But it was not as straightforward as hoped, so let's figure it out.

1. The main finding was that `rowGroupRows.ReadRows()` should intentionally __leak__ the value buffers for byte array pages, because it returns rows with slices backed by them.  It cannot re-pool the buffer while the rows exist and there is not a mechanism to track the lifetime between the two.  This is actually the prior behavior that was removed in #350 [here](https://github.com/parquet-go/parquet-go/pull/350/files#diff-4491d108deb8af17223e80d257a164bfec23ad83b6d0e041fb2c16ad84e69cc8L226)

2. It would be very simple to revert back to that behavior and not release those pages, but that causes tracebuf warning messages.   Therefore I added a more granular `ReleaseAndDetachValues()` method that releases like before, except the value buffer which just has the finalizer removed.  I.e this method is a way to signal that we are intentionally not returning this buffer to the pool.

**Discussion**:
* The memory allocation for the row-based reads is the same, across this PR and the previous commits:  in all cases we alloc a fresh value buffer for every byte-array page, and it gets GC'ed after all rows and Values pointing to it are also GC'ed. 
* A more "correct" approach is for `rowGroupRows.ReadRows()` to call `value.Clone()` as needed.  This also detaches the slices within all returned rows. But the performance loss is prohibitive.  I even tried some interning/caching, but there is not a more efficient method than simply keeping the value buffer that we already have.

Added a new benchmark to show the effect on the low-level read API (columnChunk -> Pages() -> Values() -> ReadValues()) and how the allocations were increased in #350 and restored in this PR.  I didn't see an existing benchmark that covered this.  `BenchmarkGenericReader` is flat because of the first discussion note above:  we are leaking 1 buffer per page no matter the approach via any row-based APIs.

Confirmed no more leak warnings via `PARQUETGODEBUG=tracebuf=1 go test`

**Next**
Can we think of something cleaner than `ReleaseAndDetachValues()` ?

<details>
<summary>Benchmark</summary>

```
                                        │ edd17c4.txt │             25acd53.txt              │               main.txt               │            detach.txt             │
                                        │   sec/op    │    sec/op     vs base                │    sec/op     vs base                │   sec/op     vs base              │
ColumnChunkScan/benchmarkRowType          29.08µ ± 1%    70.79µ ± 4%  +143.40% (p=0.002 n=6)    73.23µ ± 2%  +151.78% (p=0.002 n=6)   28.29µ ± 2%  -2.71% (p=0.002 n=6)
ColumnChunkScan/booleanColumn             25.58µ ± 2%    25.90µ ± 0%         ~ (p=0.288 n=6)    25.80µ ± 1%         ~ (p=0.394 n=6)   25.48µ ± 1%       ~ (p=0.093 n=6)
ColumnChunkScan/int32Column               17.38µ ± 1%    17.24µ ± 2%         ~ (p=0.818 n=6)    17.85µ ± 1%    +2.69% (p=0.002 n=6)   17.27µ ± 4%       ~ (p=0.937 n=6)
ColumnChunkScan/int64Column               20.91µ ± 1%    20.52µ ± 2%    -1.87% (p=0.011 n=6)    21.40µ ± 0%    +2.35% (p=0.002 n=6)   20.86µ ± 0%       ~ (p=0.485 n=6)
ColumnChunkScan/floatColumn               16.76µ ± 2%    16.32µ ± 5%         ~ (p=0.093 n=6)    16.82µ ± 2%         ~ (p=0.240 n=6)   16.49µ ± 1%       ~ (p=0.093 n=6)
ColumnChunkScan/doubleColumn              22.22µ ± 1%    21.95µ ± 0%    -1.21% (p=0.009 n=6)    22.38µ ± 6%         ~ (p=0.394 n=6)   22.01µ ± 2%       ~ (p=0.394 n=6)
ColumnChunkScan/byteArrayColumn           29.94µ ± 2%    72.63µ ± 2%  +142.59% (p=0.002 n=6)    72.86µ ± 1%  +143.36% (p=0.002 n=6)   29.02µ ± 5%  -3.09% (p=0.041 n=6)
ColumnChunkScan/fixedLenByteArrayColumn   23.77µ ± 1%    63.56µ ± 1%  +167.33% (p=0.002 n=6)    64.85µ ± 0%  +172.76% (p=0.002 n=6)   23.52µ ± 2%       ~ (p=0.589 n=6)
ColumnChunkScan/stringColumn              33.65µ ± 1%    79.11µ ± 6%  +135.11% (p=0.002 n=6)    79.98µ ± 0%  +137.72% (p=0.002 n=6)   33.58µ ± 2%       ~ (p=0.589 n=6)
ColumnChunkScan/indexedStringColumn       117.9µ ± 6%    111.7µ ± 1%    -5.29% (p=0.041 n=6)    112.3µ ± 1%         ~ (p=0.065 n=6)   120.1µ ± 9%       ~ (p=0.310 n=6)
ColumnChunkScan/uuidColumn                72.98µ ± 0%   114.19µ ± 1%   +56.47% (p=0.002 n=6)   116.07µ ± 1%   +59.04% (p=0.002 n=6)   72.74µ ± 1%       ~ (p=0.589 n=6)
ColumnChunkScan/timeColumn                20.62µ ± 2%    20.40µ ± 4%         ~ (p=0.132 n=6)    20.85µ ± 4%         ~ (p=0.065 n=6)   20.52µ ± 3%       ~ (p=0.619 n=6)
ColumnChunkScan/timeInMillisColumn        20.60µ ± 1%    20.43µ ± 4%         ~ (p=0.104 n=6)    20.74µ ± 1%    +0.68% (p=0.015 n=6)   20.49µ ± 0%  -0.56% (p=0.004 n=6)
ColumnChunkScan/mapColumn                 225.9µ ± 3%    416.8µ ± 1%   +84.52% (p=0.002 n=6)    420.5µ ± 1%   +86.15% (p=0.002 n=6)   221.7µ ± 3%  -1.84% (p=0.041 n=6)
ColumnChunkScan/decimalColumn             20.57µ ± 1%    20.44µ ± 3%         ~ (p=0.394 n=6)    20.78µ ± 3%    +1.04% (p=0.026 n=6)   20.50µ ± 1%       ~ (p=0.589 n=6)
ColumnChunkScan/contact                   66.64µ ± 1%   115.62µ ± 1%   +73.49% (p=0.002 n=6)   116.31µ ± 0%   +74.52% (p=0.002 n=6)   66.73µ ± 2%       ~ (p=0.937 n=6)
ColumnChunkScan/paddedBooleanColumn       26.13µ ± 2%    25.85µ ± 1%         ~ (p=0.223 n=6)    25.76µ ± 1%         ~ (p=0.167 n=6)   25.76µ ± 2%       ~ (p=0.290 n=6)
ColumnChunkScan/optionalInt32Column       28.00µ ± 1%    27.71µ ± 2%         ~ (p=0.100 n=6)    28.98µ ± 2%    +3.48% (p=0.002 n=6)   27.95µ ± 2%       ~ (p=0.818 n=6)
geomean                                   32.86µ         43.55µ        +32.54%                  44.34µ        +34.94%                 32.60µ       -0.78%

                                        │ edd17c4.txt  │            25acd53.txt             │              main.txt              │             detach.txt              │
                                        │   values/s   │  values/s    vs base               │  values/s    vs base               │   values/s     vs base              │
ColumnChunkScan/benchmarkRowType           343.8M ± 1%   141.3M ± 4%  -58.92% (p=0.002 n=6)   136.6M ± 2%  -60.28% (p=0.002 n=6)    353.4M ±  2%  +2.79% (p=0.002 n=6)
ColumnChunkScan/booleanColumn              391.0M ± 2%   386.1M ± 0%        ~ (p=0.310 n=6)   387.6M ± 1%        ~ (p=0.394 n=6)    392.4M ±  1%       ~ (p=0.093 n=6)
ColumnChunkScan/int32Column                575.4M ± 2%   580.2M ± 2%        ~ (p=0.818 n=6)   560.3M ± 1%   -2.62% (p=0.002 n=6)    579.2M ±  4%       ~ (p=0.937 n=6)
ColumnChunkScan/int64Column                478.3M ± 1%   487.5M ± 2%   +1.90% (p=0.015 n=6)   467.4M ± 0%   -2.30% (p=0.002 n=6)    479.4M ±  0%       ~ (p=0.485 n=6)
ColumnChunkScan/floatColumn                596.8M ± 2%   612.6M ± 5%        ~ (p=0.093 n=6)   594.5M ± 2%        ~ (p=0.240 n=6)    606.4M ±  1%       ~ (p=0.093 n=6)
ColumnChunkScan/doubleColumn               450.0M ± 1%   455.5M ± 0%   +1.23% (p=0.009 n=6)   446.7M ± 5%        ~ (p=0.394 n=6)    454.3M ±  2%       ~ (p=0.394 n=6)
ColumnChunkScan/byteArrayColumn            334.0M ± 2%   137.7M ± 2%  -58.78% (p=0.002 n=6)   137.2M ± 1%  -58.91% (p=0.002 n=6)    344.6M ±  5%  +3.17% (p=0.041 n=6)
ColumnChunkScan/fixedLenByteArrayColumn    420.6M ± 1%   157.3M ± 1%  -62.59% (p=0.002 n=6)   154.2M ± 0%  -63.34% (p=0.002 n=6)    425.1M ±  2%       ~ (p=0.589 n=6)
ColumnChunkScan/stringColumn               297.2M ± 1%   126.4M ± 6%  -57.47% (p=0.002 n=6)   125.0M ± 0%  -57.93% (p=0.002 n=6)    297.8M ±  2%       ~ (p=0.589 n=6)
ColumnChunkScan/indexedStringColumn        84.79M ± 6%   89.53M ± 1%   +5.58% (p=0.041 n=6)   89.02M ± 1%        ~ (p=0.065 n=6)    83.26M ± 10%       ~ (p=0.310 n=6)
ColumnChunkScan/uuidColumn                137.02M ± 0%   87.57M ± 1%  -36.09% (p=0.002 n=6)   86.16M ± 1%  -37.12% (p=0.002 n=6)   137.48M ±  1%       ~ (p=0.589 n=6)
ColumnChunkScan/timeColumn                 484.9M ± 2%   490.3M ± 4%        ~ (p=0.132 n=6)   479.6M ± 4%        ~ (p=0.065 n=6)    487.3M ±  3%       ~ (p=0.589 n=6)
ColumnChunkScan/timeInMillisColumn         485.4M ± 1%   489.5M ± 3%        ~ (p=0.132 n=6)   482.1M ± 1%   -0.68% (p=0.015 n=6)    488.1M ±  0%  +0.56% (p=0.004 n=6)
ColumnChunkScan/mapColumn                  204.7M ± 3%   111.0M ± 1%  -45.81% (p=0.002 n=6)   110.0M ± 1%  -46.28% (p=0.002 n=6)    208.6M ±  3%  +1.87% (p=0.041 n=6)
ColumnChunkScan/decimalColumn              486.2M ± 1%   489.2M ± 3%        ~ (p=0.394 n=6)   481.2M ± 3%   -1.03% (p=0.026 n=6)    487.8M ±  1%       ~ (p=0.589 n=6)
ColumnChunkScan/contact                   150.06M ± 1%   86.49M ± 1%  -42.36% (p=0.002 n=6)   85.98M ± 0%  -42.70% (p=0.002 n=6)   149.87M ±  2%       ~ (p=0.937 n=6)
ColumnChunkScan/paddedBooleanColumn        382.7M ± 2%   386.9M ± 1%        ~ (p=0.240 n=6)   388.1M ± 1%        ~ (p=0.180 n=6)    388.2M ±  2%       ~ (p=0.310 n=6)
ColumnChunkScan/optionalInt32Column        357.1M ± 1%   360.9M ± 2%        ~ (p=0.093 n=6)   345.1M ± 3%   -3.37% (p=0.002 n=6)    357.8M ±  2%       ~ (p=0.818 n=6)
geomean                                    331.3M        250.0M       -24.55%                 245.5M       -25.89%                  334.0M        +0.79%

                                        │ edd17c4.txt  │                25acd53.txt                 │                  main.txt                  │              detach.txt              │
                                        │     B/op     │      B/op       vs base                    │      B/op       vs base                    │     B/op      vs base                │
ColumnChunkScan/benchmarkRowType            593.0 ± 1%    164453.0 ± 0%  +27632.38% (p=0.002 n=6)      164453.0 ± 0%  +27632.38% (p=0.002 n=6)       593.0 ± 1%       ~ (p=1.000 n=6)
ColumnChunkScan/booleanColumn               609.0 ± 0%       609.0 ± 0%           ~ (p=1.000 n=6) ¹       609.0 ± 0%           ~ (p=1.000 n=6) ¹     609.0 ± 0%       ~ (p=1.000 n=6) ¹
ColumnChunkScan/int32Column                 593.0 ± 0%       593.0 ± 0%           ~ (p=1.000 n=6)         593.0 ± 0%           ~ (p=1.000 n=6)       593.0 ± 0%       ~ (p=1.000 n=6)
ColumnChunkScan/int64Column                 593.0 ± 0%       593.0 ± 0%           ~ (p=1.000 n=6)         593.0 ± 0%           ~ (p=1.000 n=6)       593.0 ± 0%       ~ (p=1.000 n=6)
ColumnChunkScan/floatColumn                 593.0 ± 0%       593.0 ± 0%           ~ (p=1.000 n=6) ¹       593.0 ± 0%           ~ (p=1.000 n=6) ¹     593.0 ± 0%       ~ (p=1.000 n=6) ¹
ColumnChunkScan/doubleColumn                593.0 ± 0%       593.0 ± 0%           ~ (p=1.000 n=6)         593.0 ± 0%           ~ (p=1.000 n=6)       593.0 ± 0%       ~ (p=1.000 n=6)
ColumnChunkScan/byteArrayColumn             625.0 ± 0%     49788.0 ± 0%   +7866.08% (p=0.002 n=6)       49788.0 ± 0%   +7866.08% (p=0.002 n=6)       625.0 ± 0%       ~ (p=1.000 n=6)
ColumnChunkScan/fixedLenByteArrayColumn     625.0 ± 0%    107133.0 ± 0%  +17041.28% (p=0.002 n=6)      107133.0 ± 0%  +17041.28% (p=0.002 n=6)       625.0 ± 0%       ~ (p=1.000 n=6)
ColumnChunkScan/stringColumn                625.0 ± 0%    107146.0 ± 0%  +17043.36% (p=0.002 n=6)      107146.0 ± 0%  +17043.36% (p=0.002 n=6)       625.0 ± 0%       ~ (p=1.000 n=6)
ColumnChunkScan/indexedStringColumn       240.9Ki ± 0%     280.9Ki ± 0%     +16.60% (p=0.002 n=6)       280.9Ki ± 0%     +16.60% (p=0.002 n=6)     240.9Ki ± 0%       ~ (p=1.000 n=6)
ColumnChunkScan/uuidColumn                  593.0 ± 3%    164477.0 ± 0%  +27636.42% (p=0.002 n=6)      164477.0 ± 0%  +27636.42% (p=0.002 n=6)       593.0 ± 3%       ~ (p=1.000 n=6)
ColumnChunkScan/timeColumn                  593.0 ± 0%       593.0 ± 0%           ~ (p=1.000 n=6)         593.0 ± 0%           ~ (p=1.000 n=6)       593.0 ± 0%       ~ (p=1.000 n=6)
ColumnChunkScan/timeInMillisColumn          593.0 ± 0%       593.0 ± 0%           ~ (p=1.000 n=6) ¹       593.0 ± 0%           ~ (p=1.000 n=6) ¹     593.0 ± 0%       ~ (p=1.000 n=6) ¹
ColumnChunkScan/mapColumn                 1.731Ki ± 0%   370.030Ki ± 0%  +21271.18% (p=0.002 n=6)     370.033Ki ± 0%  +21271.32% (p=0.002 n=6)     1.777Ki ± 0%  +2.62% (p=0.002 n=6)
ColumnChunkScan/decimalColumn               593.0 ± 0%       593.0 ± 0%           ~ (p=1.000 n=6) ¹       593.0 ± 0%           ~ (p=1.000 n=6) ¹     593.0 ± 0%       ~ (p=1.000 n=6)
ColumnChunkScan/contact                     643.0 ± 0%    205502.0 ± 0%  +31859.88% (p=0.002 n=6)      205502.0 ± 0%  +31859.88% (p=0.002 n=6)       643.0 ± 0%       ~ (p=1.000 n=6) ¹
ColumnChunkScan/paddedBooleanColumn         609.0 ± 0%       609.0 ± 0%           ~ (p=1.000 n=6) ¹       609.0 ± 0%           ~ (p=1.000 n=6) ¹     609.0 ± 0%       ~ (p=1.000 n=6) ¹
ColumnChunkScan/optionalInt32Column         673.0 ± 0%       673.0 ± 0%           ~ (p=1.000 n=6)         673.0 ± 0%           ~ (p=1.000 n=6)       673.0 ± 0%       ~ (p=1.000 n=6)
geomean                                     901.7          6.956Ki         +689.93%                     6.956Ki         +689.93%                     903.0       +0.14%
¹ all samples are equal

                                        │ edd17c4.txt │             25acd53.txt              │               main.txt               │             detach.txt             │
                                        │  allocs/op  │  allocs/op   vs base                 │  allocs/op   vs base                 │ allocs/op   vs base                │
ColumnChunkScan/benchmarkRowType           9.000 ± 0%   10.000 ± 0%  +11.11% (p=0.002 n=6)     10.000 ± 0%  +11.11% (p=0.002 n=6)     9.000 ± 0%       ~ (p=1.000 n=6) ¹
ColumnChunkScan/booleanColumn              9.000 ± 0%    9.000 ± 0%        ~ (p=1.000 n=6) ¹    9.000 ± 0%        ~ (p=1.000 n=6) ¹   9.000 ± 0%       ~ (p=1.000 n=6) ¹
ColumnChunkScan/int32Column                9.000 ± 0%    9.000 ± 0%        ~ (p=1.000 n=6) ¹    9.000 ± 0%        ~ (p=1.000 n=6) ¹   9.000 ± 0%       ~ (p=1.000 n=6) ¹
ColumnChunkScan/int64Column                9.000 ± 0%    9.000 ± 0%        ~ (p=1.000 n=6) ¹    9.000 ± 0%        ~ (p=1.000 n=6) ¹   9.000 ± 0%       ~ (p=1.000 n=6) ¹
ColumnChunkScan/floatColumn                9.000 ± 0%    9.000 ± 0%        ~ (p=1.000 n=6) ¹    9.000 ± 0%        ~ (p=1.000 n=6) ¹   9.000 ± 0%       ~ (p=1.000 n=6) ¹
ColumnChunkScan/doubleColumn               9.000 ± 0%    9.000 ± 0%        ~ (p=1.000 n=6) ¹    9.000 ± 0%        ~ (p=1.000 n=6) ¹   9.000 ± 0%       ~ (p=1.000 n=6) ¹
ColumnChunkScan/byteArrayColumn            9.000 ± 0%   10.000 ± 0%  +11.11% (p=0.002 n=6)     10.000 ± 0%  +11.11% (p=0.002 n=6)     9.000 ± 0%       ~ (p=1.000 n=6) ¹
ColumnChunkScan/fixedLenByteArrayColumn    10.00 ± 0%    11.00 ± 0%  +10.00% (p=0.002 n=6)      11.00 ± 0%  +10.00% (p=0.002 n=6)     10.00 ± 0%       ~ (p=1.000 n=6) ¹
ColumnChunkScan/stringColumn               9.000 ± 0%   10.000 ± 0%  +11.11% (p=0.002 n=6)     10.000 ± 0%  +11.11% (p=0.002 n=6)     9.000 ± 0%       ~ (p=1.000 n=6) ¹
ColumnChunkScan/indexedStringColumn        16.00 ± 0%    17.00 ± 0%   +6.25% (p=0.002 n=6)      17.00 ± 0%   +6.25% (p=0.002 n=6)     16.00 ± 0%       ~ (p=1.000 n=6) ¹
ColumnChunkScan/uuidColumn                 9.000 ± 0%   10.000 ± 0%  +11.11% (p=0.002 n=6)     10.000 ± 0%  +11.11% (p=0.002 n=6)     9.000 ± 0%       ~ (p=1.000 n=6) ¹
ColumnChunkScan/timeColumn                 9.000 ± 0%    9.000 ± 0%        ~ (p=1.000 n=6) ¹    9.000 ± 0%        ~ (p=1.000 n=6) ¹   9.000 ± 0%       ~ (p=1.000 n=6) ¹
ColumnChunkScan/timeInMillisColumn         9.000 ± 0%    9.000 ± 0%        ~ (p=1.000 n=6) ¹    9.000 ± 0%        ~ (p=1.000 n=6) ¹   9.000 ± 0%       ~ (p=1.000 n=6) ¹
ColumnChunkScan/mapColumn                  27.00 ± 0%    31.00 ± 0%  +14.81% (p=0.002 n=6)      31.00 ± 0%  +14.81% (p=0.002 n=6)     27.00 ± 0%       ~ (p=1.000 n=6) ¹
ColumnChunkScan/decimalColumn              9.000 ± 0%    9.000 ± 0%        ~ (p=1.000 n=6) ¹    9.000 ± 0%        ~ (p=1.000 n=6) ¹   9.000 ± 0%       ~ (p=1.000 n=6) ¹
ColumnChunkScan/contact                    9.000 ± 0%   10.000 ± 0%  +11.11% (p=0.002 n=6)     10.000 ± 0%  +11.11% (p=0.002 n=6)     9.000 ± 0%       ~ (p=1.000 n=6) ¹
ColumnChunkScan/paddedBooleanColumn        9.000 ± 0%    9.000 ± 0%        ~ (p=1.000 n=6) ¹    9.000 ± 0%        ~ (p=1.000 n=6) ¹   9.000 ± 0%       ~ (p=1.000 n=6) ¹
ColumnChunkScan/optionalInt32Column        11.00 ± 0%    11.00 ± 0%        ~ (p=1.000 n=6) ¹    11.00 ± 0%        ~ (p=1.000 n=6) ¹   11.00 ± 0%       ~ (p=1.000 n=6) ¹
geomean                                    10.05         10.52        +4.67%                    10.52        +4.67%                   10.05       +0.00%
¹ all samples are equal

```
</details>

### CODE REVIEW

File: column_chunk_test.go [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+	benchmarkColumnChunkScan[timeColumn](b)
+	benchmarkColumnChunkScan[timeInMillisColumn](b)
+	benchmarkColumnChunkScan[mapColumn](b)
+	benchmarkColumnChunkScan[decimalColumn](b)
+	benchmarkColumnChunkScan[contact](b)
+	benchmarkColumnChunkScan[paddedBooleanColumn](b)
+	benchmarkColumnChunkScan[optionalInt32Column](b)
+}
+
+func benchmarkColumnChunkScan[Row generator[Row]](b *testing.B) {
```
Comment (achille-roussel) [inline column_chunk_test.go:40]: Do you think we could use [AllocsPerRun](https://pkg.go.dev/testing#AllocsPerRun) here to ensure that we catch those regressions in the future?

Comment (mdisibio) [reply column_chunk_test.go:40]: Are you thinking something like a test that performs a similar columnChunk read, and fails if AllocsPerRun is over threshold X ?  Looking at the benchmarks, allocs/op only increases by 1 for each involved column, perhaps because the test file is still quite small and contains 1 page.  B/op stands out more.  But I can try it and see if there is enough consistency to catch it.

Comment (mdisibio) [reply column_chunk_test.go:40]: Did some testing and allocs per run is a little implementation specific to test on I think. For example some types are 8 allocs per ReadPage() call, others like `mapColumn` are 27.  When re-adding the make() in decodeDataPage, it only increases 1, so the signal is not very strong.

Instead, I tried an alternative which measures the total non-dictionary alloc per page.  This is much stronger. When pooling is working the avg alloc per page is 300-600 bytes, via structs like the format.PageHeader, bufferedPage, and FilePages.  When the make() re-added, any bytearray columns have allocs of 100KB+ per page. A much stronger signal that something isn't working.

Pushed the test, it is working well locally, but totally failing in CI :)  Will dig into CI next.  A bit mystified so far, maybe concurrency issue?  Is there anything different about how CI runs tests, or pooling on the s390x for example?

Here is the test with the make() re-added and it's failing:

```
$ go test -v -run=TestColumnChunkAllocs                    
=== RUN   TestColumnChunkAllocs
=== RUN   TestColumnChunkAllocs/benchmarkRowType
    column_chunk_test.go:176: avg alloc per page should be under 1KB, got 205172
=== RUN   TestColumnChunkAllocs/booleanColumn
=== RUN   TestColumnChunkAllocs/int32Column
=== RUN   TestColumnChunkAllocs/int64Column
=== RUN   TestColumnChunkAllocs/floatColumn
=== RUN   TestColumnChunkAllocs/doubleColumn
=== RUN   TestColumnChunkAllocs/byteArrayColumn
    column_chunk_test.go:176: avg alloc per page should be under 1KB, got 115200
=== RUN   TestColumnChunkAllocs/fixedLenByteArrayColumn
    column_chunk_test.go:176: avg alloc per page should be under 1KB, got 254432
=== RUN   TestColumnChunkAllocs/stringColumn
    column_chunk_test.go:176: avg alloc per page should be under 1KB, got 172487
=== RUN   TestColumnChunkAllocs/indexedStringColumn
=== RUN   TestColumnChunkAllocs/uuidColumn
    column_chunk_test.go:176: avg alloc per page should be under 1KB, got 205198
=== RUN   TestColumnChunkAllocs/timeColumn
=== RUN   TestColumnChunkAllocs/timeInMillisColumn
=== RUN   TestColumnChunkAllocs/mapColumn
    column_chunk_test.go:176: avg alloc per page should be under 1KB, got 132676
=== RUN   TestColumnChunkAllocs/decimalColumn
=== RUN   TestColumnChunkAllocs/contact
    column_chunk_test.go:176: avg alloc per page should be under 1KB, got 254361
=== RUN   TestColumnChunkAllocs/paddedBooleanColumn
=== RUN   TestColumnChunkAllocs/optionalInt32Column
--- FAIL: TestColumnChunkAllocs (0.11s)
    --- FAIL: TestColumnChunkAllocs/benchmarkRowType (0.01s)
    --- PASS: TestColumnChunkAllocs/booleanColumn (0.00s)
    --- PASS: TestColumnChunkAllocs/int32Column (0.00s)
    --- PASS: TestColumnChunkAllocs/int64Column (0.00s)
    --- PASS: TestColumnChunkAllocs/floatColumn (0.00s)
    --- PASS: TestColumnChunkAllocs/doubleColumn (0.00s)
    --- FAIL: TestColumnChunkAllocs/byteArrayColumn (0.00s)
    --- FAIL: TestColumnChunkAllocs/fixedLenByteArrayColumn (0.00s)
    --- FAIL: TestColumnChunkAllocs/stringColumn (0.01s)
    --- PASS: TestColumnChunkAllocs/indexedStringColumn (0.01s)
    --- FAIL: TestColumnChunkAllocs/uuidColumn (0.01s)
    --- PASS: TestColumnChunkAllocs/timeColumn (0.00s)
    --- PASS: TestColumnChunkAllocs/timeInMillisColumn (0.00s)
    --- FAIL: TestColumnChunkAllocs/mapColumn (0.04s)
    --- PASS: TestColumnChunkAllocs/decimalColumn (0.00s)
    --- FAIL: TestColumnChunkAllocs/contact (0.01s)
    --- PASS: TestColumnChunkAllocs/paddedBooleanColumn (0.00s)
    --- PASS: TestColumnChunkAllocs/optionalInt32Column (0.00s)
FAIL
exit status 1
FAIL	github.com/parquet-go/parquet-go	0.323s
```

And then with the make removed:
```
$ go test -v -run=TestColumnChunkAllocs
=== RUN   TestColumnChunkAllocs
=== RUN   TestColumnChunkAllocs/benchmarkRowType
=== RUN   TestColumnChunkAllocs/booleanColumn
=== RUN   TestColumnChunkAllocs/int32Column
=== RUN   TestColumnChunkAllocs/int64Column
=== RUN   TestColumnChunkAllocs/floatColumn
=== RUN   TestColumnChunkAllocs/doubleColumn
=== RUN   TestColumnChunkAllocs/byteArrayColumn
=== RUN   TestColumnChunkAllocs/fixedLenByteArrayColumn
=== RUN   TestColumnChunkAllocs/stringColumn
=== RUN   TestColumnChunkAllocs/indexedStringColumn
=== RUN   TestColumnChunkAllocs/uuidColumn
=== RUN   TestColumnChunkAllocs/timeColumn
=== RUN   TestColumnChunkAllocs/timeInMillisColumn
=== RUN   TestColumnChunkAllocs/mapColumn
=== RUN   TestColumnChunkAllocs/decimalColumn
=== RUN   TestColumnChunkAllocs/contact
=== RUN   TestColumnChunkAllocs/paddedBooleanColumn
=== RUN   TestColumnChunkAllocs/optionalInt32Column
--- PASS: TestColumnChunkAllocs (0.10s)
    --- PASS: TestColumnChunkAllocs/benchmarkRowType (0.01s)
    --- PASS: TestColumnChunkAllocs/booleanColumn (0.00s)
    --- PASS: TestColumnChunkAllocs/int32Column (0.00s)
    --- PASS: TestColumnChunkAllocs/int64Column (0.00s)
    --- PASS: TestColumnChunkAllocs/floatColumn (0.00s)
    --- PASS: TestColumnChunkAllocs/doubleColumn (0.00s)
    --- PASS: TestColumnChunkAllocs/byteArrayColumn (0.00s)
    --- PASS: TestColumnChunkAllocs/fixedLenByteArrayColumn (0.00s)
    --- PASS: TestColumnChunkAllocs/stringColumn (0.01s)
    --- PASS: TestColumnChunkAllocs/indexedStringColumn (0.01s)
    --- PASS: TestColumnChunkAllocs/uuidColumn (0.01s)
    --- PASS: TestColumnChunkAllocs/timeColumn (0.00s)
    --- PASS: TestColumnChunkAllocs/timeInMillisColumn (0.00s)
    --- PASS: TestColumnChunkAllocs/mapColumn (0.04s)
    --- PASS: TestColumnChunkAllocs/decimalColumn (0.00s)
    --- PASS: TestColumnChunkAllocs/contact (0.01s)
    --- PASS: TestColumnChunkAllocs/paddedBooleanColumn (0.00s)
    --- PASS: TestColumnChunkAllocs/optionalInt32Column (0.00s)
PASS
ok  	github.com/parquet-go/parquet-go	0.291s
```

Comment (mdisibio) [reply column_chunk_test.go:40]: OK, the issue is that sync.Pool doesn't work under the race detector, going even as far as to [randomly drop items](https://go.dev/src/sync/pool.go#L105).  Excluded the new test via build flags, which has fixed most of CI.  Ideally we would run this test in CI, but not sure if there is a great option.  We could run all tests twice, with and without the race detector.

Not sure about the continued failing in the s390x tests, the errors are similar to pooling not working, so perhaps there is a platform-specific behavior.

**Comment by mdisibio** [comment]
This is ready for review.  The newly added allocation test works well locally, but the build flags more-or-less exclude it from CI due to the sync.Pool and race detector interaction.  So it remains a useful tool for debugging or bisecting, but not catching regressions ahead of time.  Despite, this PR does patch up the allocation itself, and the remaining tests with page leaks, so that `PARQUETGODEBUG=tracebuf=1 go test` is clean.  Happy to adjust naming/location/style of anything.

**Comment by mdisibio** [comment]
> * Could we solve this with an `AppendClone` API?
> having the application pass the buffer to write the values to

In my understanding, the primary user of this is not the application, but our own concrete implementations of row readers. i.e.

```go
type RowReader interface {
	ReadRows([]Row) (int, error)
}
```

A single call to ReadRows may cross multiple pages and return objects with embedded strings from any of them.

I think the current approach has the best possible performance, because we are continuing with the already populated page buffer and giving it to the GC, and make()ing a fresh one for the next page.    Other approaches are likely making trade-offs from that.

AppendClone would definitely be an improvement over Clone.  However it would effectively be copying the underlying buffer in small increments.  Something like `Page.Clone()` could do the same, more efficiently.  

Each of the above approaches are logically a make() + copy(), whereas the current PR is just a make().

**Comment by mdisibio** [comment]
Another option is we could unexport `func ReleaseAndDetachValues(page Page)` since it is only called by the row reader implementation for now.   This restores the prior reuse/malloc behavior before commit 25acd53, and doesn't widen the public API.

**Comment by achille-roussel** [comment]
Sounds good 👍

**Comment by fpetkovski** [comment]
Does this mean I can now use `ReleaseAndDetachValues(page)` to release pages for byte arrays without needing to clone values read from the page?

**Comment by mdisibio** [comment]
> Does this mean I can now use `ReleaseAndDetachValues(page)` to release pages for byte arrays without needing to clone values read from the page?

We unexported it, so it's not part of the public API yet.  But callers could already accomplish that by not `Release()`ing pages returned from ReadPage(). 

The reasons for `releaseAndDetachValues()` are (1) mainly book-keeping, as we intentionally want to do this from the row-based apis i.e. `GenericReader[T].ReadRows()` but not trigger warnings in tests about leaked buffers and (2) there is a small benefit from being able to repool the other buffers like the offset buffer, and only relinquishing the values buffer.
