### PR TITLE
fix SortingWriter

### LINKED ISSUE #82: `SortingWriter` only writes a single row group
While using the `SortingWriter` API I noticed that my files were awfully small. I expected them to be >1GiB but they were around 2 MiB. This did not happen previously when I used it a few months ago. 

I wrote up a short repro in Go. 
I used [lz4_raw_compressed_larger.parquet](https://github.com/parquet-go/parquet-go/files/13049604/lz4_raw_compressed_larger.zip) from the [apache/parquet-testing](https://github.com/apache/parquet-testing) repo. The script reads this file, which has 10,000 rows, and then writes a new copy of the input using a `SortingWriter`. We set `sortRowCount` to 1000 in the `SortingWriter` to reproduce the issue. The issue is not observed when `sortRowCount` is greater than 10,000. 
With these settings, we observe only 1024 rows being written, where we expected all 10,000. 

<details>

<summary>
Code
</summary>

```go
package main

import (
	"os"

	"github.com/parquet-go/parquet-go"
	"github.com/sirupsen/logrus"
)

func main() {
	type Record struct {
		A string `parquet:"a"`
	}

	fi, err := os.Open("lz4_raw_compressed_larger.parquet")
	if err != nil {
		logrus.WithError(err).Fatal("couldn't open input")
	}

	pr := parquet.NewGenericReader[Record](fi, parquet.DefaultReaderConfig())
	defer pr.Close()

	out, err := os.Create("test.parquet")
	if err != nil {
		logrus.WithError(err).Fatal("couldn't create output file")
	}

	pw := parquet.NewSortingWriter[Record](
		out,
		1000,
		parquet.SortingWriterConfig(
			parquet.SortingColumns(parquet.Ascending("a")),
		),
	)

	if _, err := parquet.CopyRows(pw, pr); err != nil {
		logrus.WithError(err).Fatal("couldn't copy rows")
	}

	if err := pw.Close(); err != nil {
		logrus.WithError(err).Fatal("couldn't close parquet writer")
	}

	if err := out.Sync(); err != nil {
		logrus.WithError(err).Fatal("couldn't sync to disk")
	}

	result := parquet.NewGenericReader[Record](out, parquet.DefaultReaderConfig())
	defer result.Close()
	if result.NumRows() != pr.NumRows() {
		logrus.Fatalf("resulting parquet file did not have expected rows (expected %d, got %d)", pr.NumRows(), result.NumRows())
	}
}

// ❯ go run .
// FATA[0000] resulting parquet file did not have expected rows (expected 10000, got 1024)
```
</details>

While digging into the issue, I noticed a piece of code that was added recently:
https://github.com/parquet-go/parquet-go/blob/d42d339c3f6a0f8feb155ab93d725910c35bc98c/merge.go#L111-L118

It appears that it was added to fix a data corruption issue in #31. In any case, I commented out this piece of code, so as to make `CopyRows` fall back to the existing `RowReader` API, and that fixed the above repro script I made. 

My conclusion is that the addition of `mergeBuffer` probably introduced the bug I am seeing right now.

### LINKED ISSUE #98: Sorting writer is not able to create multiple row groups
I am trying to control number of rows written per row group in an output file but it does not seem to work. Input file has >570000 records. Not sure if I am missing anything in below code. Can someone help please? 

```
package main

import (
	"fmt"
	"os"
	"reflect"

	"github.com/parquet-go/parquet-go"
)

func main() {
	file1 := "large_file.parquet"
	file2 := "large_file_control_row_group.parquet"
	f1, err := os.Open(file1)
	if err != nil {
		panic(err)
	}
	defer f1.Close()

	s1, err := os.Stat(file1)
	if err != nil {
		panic(err)
	}

	p1, err := parquet.OpenFile(f1, s1.Size())
	if err != nil {
		panic(err)
	}
	if size := p1.Size(); size != s1.Size() {
		fmt.Errorf("file size mismatch: want=%d got=%d", s1.Size(), size)
		panic(err)
	}
	schema := p1.Schema()
	fmt.Println("file1 schema: ", schema)
	fmt.Println("file1 gotype", schema.GoType())

	reader := parquet.NewGenericReader[any](f1, &parquet.ReaderConfig{
		Schema: schema,
	})
	numRows := reader.NumRows()
	out := make([]parquet.Row, 0)
	for _, rowgroup := range p1.RowGroups() {
		out1 := make([]parquet.Row, rowgroup.NumRows())
		_, err := reader.ReadRows(out1)
		if err != nil {
			panic(err)
		}
		out = append(out, out1...)
	}
	fmt.Println("file1 numRows", numRows)
	fmt.Println("file1 out= ", len(out))
	fmt.Println("file1 out= ", reflect.TypeOf(out[0]))

	f2, err := os.Create(file2)
	if err != nil {
		panic(err)
	}
	defer f2.Close()

	pw := parquet.NewSortingWriter[any](f2, int64(50000),
		&parquet.WriterConfig{
			//	PageBufferSize: 2560,
			Schema:      schema,
			Compression: &parquet.Zstd,
		})
	n, err := pw.WriteRows(out)
	if err != nil {
		panic( fmt.Sprintf("failed to write parquet file  err: ", file2, err))
	}
	fmt.Println("written rows to parquet file : ", n, file2)
	if err := pw.Close(); err != nil {
		panic( fmt.Sprintf("failed to close parquet file, err:", file2, err))
	}
	fmt.Println("closed parquet file", file2)
}
```

### PR DESCRIPTION
**Pull request by gernest**
Closes #98
Closes #82

### CODE REVIEW

File: sorting_test.go [hunk 1]
```diff
@@ -257,3 +258,41 @@ func assertRowsEqualByRow[T any](t *testing.T, rowsGot, rowsWant []T) {
 		t.Error(count, "rows mismatched out of", len(rowsWant), "total")
 	}
 }
+
+func TestIssue_82(t *testing.T) {
+	type Record struct {
+		A string `parquet:"a"`
+	}
+
+	fi, err := os.Open("testdata/lz4_raw_compressed_larger.parquet")
```
Comment (fpetkovski) [inline sorting_test.go:267]: I would add an assertion that this file has more than 1 row group because that's not visible from the test itself.

File: sorting_test.go [hunk 2]
```diff
@@ -257,3 +258,41 @@ func assertRowsEqualByRow[T any](t *testing.T, rowsGot, rowsWant []T) {
...
+		t.Fatal(err)
+	}
+
+	if err := pw.Close(); err != nil {
+		t.Fatal(err)
+	}
+
+	result := parquet.NewGenericReader[Record](bytes.NewReader(out.Bytes()), parquet.DefaultReaderConfig())
+	defer result.Close()
+	if result.NumRows() != pr.NumRows() {
```
Comment (fpetkovski) [inline sorting_test.go:295]: Do we want to sort each row group in memory and compare results with the sorting writer? Or do we have other tests which verify that?

**Comment by gernest** [comment]
@fpetkovski thanks for the review. PTAL , I have addressed all your comments.

File: sorting_test.go (hunk 1 above)
Comment (gernest) [reply sorting_test.go:267]: @fpetkovski  That wont be necessary. The number of row groups was not the actual issue. The issue is about mismatch between the rows written/read. 

Go back to the OP ticket you will notice he uses the same test case file as I do there. You can consistently reproduce the issue by running the sample they provided.

Comment (fpetkovski) [reply sorting_test.go:267]: Got it, thanks for the clarification.

**Review by fpetkovski — APPROVED** [review]
