### PR TITLE
Fix seeking to row start when row values break across two or more data pages

### LINKED ISSUE #276: Errors reading list elements in V1 data pages
Given a parquet file where a column has an array data type (e.g. `int64_array []int64`), the column schema would look like this:

```
  optional group int64_array (LIST) {
    repeated group list {
      optional int64 element;
    }
  }
```

When reading such a list column, with V1 data pages, if a row's values do not start immediately at the beginning of a V1 data page, then reading the values produces a truncated array with length less than expected.

Reproducer:

- parquet file has a column `int64_array` with the above schema. The sample file has 5 rows, each row is an array of 13 values. This is how rows/values are laid out across pages:

```
page: 1, num rows in page: 1, num values in page: 9
page: 2, num rows in page: 1, num values in page: 9
page: 3, num rows in page: 0, num values in page: 8
page: 4, num rows in page: 1, num values in page: 9
page: 5, num rows in page: 1, num values in page: 9
page: 6, num rows in page: 0, num values in page: 8
page: 7, num rows in page: 1, num values in page: 9
page: 8, num rows in page: 0, num values in page: 4
```

So the second row (index 1) starts in the second page at value index 4.

- the test seeks to row 1. The returned `int64_array` has length of 4 instead of 13. Reason is that instead of seeking to the beginning of the row values at page 2, index 4, seeking ends at the beginning of page 2: this way, the array returns values at indexes [0,4) of page 2 (the four last values of first row actually)

Full test source

```
func TestListElementsAcrossPagesRepro(t *testing.T) {
	type Row struct {
		Id       string  `parquet:"id"`
		IntArray []int64 `parquet:"int64_array,optional,list"`
	}
	f, err := os.Open("testdata/gen_9.parquet")
	if err != nil {
		t.Fatalf("Failed to open file: %v", err)
	}
	printColumnLayout(t, f)
	pr := parquet.NewGenericReader[*Row](f)
	err = pr.SeekToRow(1)
	if err != nil {
		t.Fatalf("Failed to seek to row 1: %v", err)
	}
	rows := make([]*Row, 1)
	n, err := pr.Read(rows)
	if n != 1 {
		t.Fatalf("Read returned %d rows, want 1", n)
	}
	if len(rows[0].IntArray) != 13 {
		t.Fatalf("Read returned %d values in array, want 13", len(rows[0].IntArray))
	}
}

func printColumnLayout(t *testing.T, f *os.File) {
	if t.Failed() {
		return
	}
	stats, _ := f.Stat()
	pqFile, err := parquet.OpenFile(f, stats.Size())
	if err != nil {
		t.Fatalf("Failed to open file: %v", err)
	}
	col := pqFile.Root()
	col = col.Column("int64_array").Column("list").Column("element")
	pages := col.Pages()
	defer pages.Close()
	pageCounter := 0
	for {
		pageCounter++
		p, err := pages.ReadPage()
		if err != nil {
			if err != io.EOF {
				t.Error(err)
			}
			break
		}
		t.Logf("page: %d, num rows in page: %d, num values in page: %d", pageCounter, p.NumRows(), p.NumValues())
		parquet.Release(p)
	}
}
```

File `gen_9.parquet` is attached in zip file

[gen_9.parquet.zip](https://github.com/user-attachments/files/20033391/gen_9.parquet.zip)

### PR DESCRIPTION
**Pull request by vbekiaris**
As described in #276, when parsing V1 data pages with lists of elements, it's possible that a new page does not start with a new row. This PR addresses this issue by making sure that when seeking to a row:
- if the page does not contain any rows, it is skipped
- if the page contains some rows, then seeking continues until the first value with repetition level == 0 (instead of stopping seeking at the beginning of the page).

Fixes #276

### CODE REVIEW

**Review by glkz — APPROVED** [review]

File: file.go [hunk 1]
```diff
@@ -838,7 +841,27 @@ func (f *FilePages) ReadPage() (Page, error) {
...
+			if !seekToRowStart {
+				// keep reading values from beginning of new page
+				return page, nil
+			} else {
+				if page.NumRows() == 0 {
+					// if current page does not have any rows, continue until a page with at least 1 row is reached
+					Release(page)
+					continue
+				}
+				// In V1 data pages, new page does not necessarily start with a new row.
```
Comment (joe-elliott) [inline file.go:858]: is this a v1 possibility only? page.Slice() can be an expensive operation b/c (depending on the page type) it can loop through all repetition levels to find row 0 and row page.NumRow().

if it's v1 only should we test for that before slicing?

File: file.go [hunk 2]
```diff
@@ -838,7 +841,27 @@ func (f *FilePages) ReadPage() (Page, error) {
 
 		f.index++
 		if f.skip == 0 {
-			return page, nil
+			// f.skip==0 can be true:
+			//  (1) while reading a row of a column which has multiple values (ie. X.list.element) and values continue
+			//  across pages. In that case we just want to keep reading without skipping any values.
+			//  (2) when seeking to a specific row and trying to reach the start offset of the first
+			//  row in a new page.
+			if !seekToRowStart {
```
Comment (joe-elliott) [inline file.go:849]: to reduce if nesting can we do something like:

```
f.index++
if !seekToRowStart {
  // not seeking. do normal things and return
}

if f.skip == 0 {
  // seeking. do seeking things
}
```

File: file.go (hunk 1 above)
Comment (vbekiaris) [reply file.go:858]: Yes, that is my understanding. [v2 data pages](https://github.com/apache/parquet-format/blob/master/src/main/thrift/parquet.thrift#L725-L730) always start at a row boundary.

Based on this, I have restructured the if-else so it's hopefully easier to follow.

Comment (joe-elliott) [reply file.go]: could we use the repetitionlevels in the page? something like this (except with more bounds checking) would be a direct check on the actual situation that we're correcting for. 

```
// this page doesn't start on a row boundary and we're seeking
if seekToRowStart && page.RepetitionLevels()[0] != 0 {
}
```

i think this would work

Comment (vbekiaris) [reply file.go]: thanks, I added the repetition level check to avoid the page slice if the page starts at row boundary [here](https://github.com/parquet-go/parquet-go/pull/277/commits/99e961f01ca0a311a696bbf5742723e3d961b19b). At this point, `seekToRowStart` is known to be `true` so no need to check that too.

File: file.go [hunk 3]
```diff
@@ -838,7 +841,30 @@ func (f *FilePages) ReadPage() (Page, error) {
...
+			//  across pages. In that case we just want to keep reading without skipping any values.
+			//  (2) when seeking to a specific row and trying to reach the start offset of the first
+			//  row in a new page.
+			if !seekToRowStart || header.Type != format.DataPage {
+				// keep reading values from beginning of new page
+				return page, nil
+			}
+			// We need to seek to beginning of row.
+			// V1 data pages do not necessarily start at a row boundary.
+			if page.NumRows() == 0 {
```
Comment (joe-elliott) [inline file.go:855]: this is a behavior change and potentially a bug? if we're not seeking it prevents us from returning a page with no rows which may occur on v1 pages? (i'm not sure)

this is safe to remove though. if we are seeking f.skip will never be 0 on a page with 0 rows b/c of the way we subtract numRows here:

https://github.com/parquet-go/parquet-go/blob/main/file.go#L846-L857

Thank you for this work! I think it's quite close.

Comment (vbekiaris) [reply file.go:855]: If we are not seeking to the start of a row, then the [previous condition](https://github.com/parquet-go/parquet-go/pull/277/files#diff-33f8fbc61d6878200e61e69725cd724475a0c9dbb73bc63fcfc913a5651764feR849) is `true`, we have already returned the current `page` and this code won't be executed. But please let me know if I maybe misunderstood your comment.

Comment (joe-elliott) [reply file.go:855]: my bad! you are correct. i misread this code 🙏

**Review by joe-elliott — APPROVED** [review]
thanks for this fix!
